//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilion()
        {
            this.Rents = new HashSet<Rents>();
        }
    
        public int ID_Center { get; set; }
        public string Number_Pavilion { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Status_Pavilion { get; set; }
        public Nullable<double> Square { get; set; }
        public Nullable<double> Cost_per_sq_m { get; set; }
        public Nullable<double> Added_value_factor { get; set; }
    
        public virtual Shop_Centers Shop_Centers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rents> Rents { get; set; }
    }
}
