//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int ID_Rent { get; set; }
        public int ID_Renters { get; set; }
        public int ID_Center { get; set; }
        public int ID_Employees { get; set; }
        public string Number_Pavilion { get; set; }
        public string Status_Rent { get; set; }
        public System.DateTime Beginning_Rent { get; set; }
        public System.DateTime Ending_Rent { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Pavilion Pavilion { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
