//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Centers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_Centers()
        {
            this.Pavilion = new HashSet<Pavilion>();
        }
    
        public int ID_Center { get; set; }
        public string Name_Center { get; set; }
        public string Status_Center { get; set; }
        public Nullable<int> Quantity_pavilions { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<double> Coef_Add_Price { get; set; }
        public Nullable<int> Number_floors { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pavilion> Pavilion { get; set; }
    }
}
